//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdAuxiliaryRelay
    {
        public string Rating { get; set; }
        public int ID { get; set; }
    
        public virtual mdPanelComponent mdPanelComponent { get; set; }
    }
}
