//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdCircuitBreaker
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int PrimaryEquipmentId { get; set; }
        public string NominalCurrent { get; set; }
        public string Unit { get; set; }
        public string Spec { get; set; }
    
        public virtual mdPrimaryEquipment mdPrimaryEquipment { get; set; }
    }
}
