//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdContactDetail
    {
        public string Name { get; set; }
        public string Designation { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string FaxNo { get; set; }
        public string OfficePhone { get; set; }
        public string Address { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int ContactDetailsID { get; set; }
        public Nullable<int> LogoDetailID { get; set; }
    
        public virtual mdLogoDetail mdLogoDetail { get; set; }
    }
}
