//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdCore
    {
        public string Name { get; set; }
        public Nullable<int> NoOfPrimary { get; set; }
        public string Ratio { get; set; }
        public string Primary1 { get; set; }
        public string Primary2 { get; set; }
        public string Primary3 { get; set; }
        public string Primary4 { get; set; }
        public string Primary5 { get; set; }
        public string Primary6 { get; set; }
        public string Secondary { get; set; }
        public string Class { get; set; }
        public string AccuracyLimitFactor { get; set; }
        public string Burden { get; set; }
        public string KneePoint { get; set; }
        public string MagCurrent { get; set; }
        public string CtResistence { get; set; }
        public string Function { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int CoreID { get; set; }
        public Nullable<int> PrimaryEquipmentId { get; set; }
    
        public virtual mdCurrentTransformer mdCurrentTransformer { get; set; }
    }
}
