//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdCustomerDeliverableVoltage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdCustomerDeliverableVoltage()
        {
            this.mdCustomerDeliverableDates = new HashSet<mdCustomerDeliverableDate>();
        }
    
        public int ID { get; set; }
        public string Voltage { get; set; }
        public int ProjectID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdCustomerDeliverableDate> mdCustomerDeliverableDates { get; set; }
        public virtual mdProject mdProject { get; set; }
    }
}
