//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdCurrentTransformer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdCurrentTransformer()
        {
            this.mdCores = new HashSet<mdCore>();
        }
    
        public string DummyColumn { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int PrimaryEquipmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdCore> mdCores { get; set; }
        public virtual mdPrimaryEquipment mdPrimaryEquipment { get; set; }
    }
}
