//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdCustomerDeliverableDate
    {
        public int ID { get; set; }
        public int CustomerDeliverableVoltageID { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> DateOfReceived { get; set; }
        public int CustomerDeliverableID { get; set; }
        public bool NotApplicable { get; set; }
        public bool Planned { get; set; }
        public bool Received { get; set; }
        public string Remark { get; set; }
    
        public virtual mdCustomerDeliverableVoltage mdCustomerDeliverableVoltage { get; set; }
        public virtual msCustomerDeliverable msCustomerDeliverable { get; set; }
    }
}
