//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdLogoDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdLogoDetail()
        {
            this.mdContactDetails = new HashSet<mdContactDetail>();
            this.mdDoubleLogoes = new HashSet<mdDoubleLogo>();
            this.mdDoubleLogoes1 = new HashSet<mdDoubleLogo>();
            this.mdSingleLogoes = new HashSet<mdSingleLogo>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        public int LogoDetailID { get; set; }
        public string Type { get; set; }
        public byte[] Logo { get; set; }
        public bool AddToTemplate { get; set; }
        public string LogoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdContactDetail> mdContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdDoubleLogo> mdDoubleLogoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdDoubleLogo> mdDoubleLogoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdSingleLogo> mdSingleLogoes { get; set; }
    }
}
