//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdMasterProjectSchedule
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DesignStart { get; set; }
        public Nullable<System.DateTime> SchematicDrawingSubmission { get; set; }
        public Nullable<System.DateTime> ManufacturingDocs { get; set; }
        public Nullable<System.DateTime> ManufacturingStart { get; set; }
        public Nullable<System.DateTime> ManufacturingEnd { get; set; }
        public Nullable<System.DateTime> InternalTestingStart { get; set; }
        public Nullable<System.DateTime> InternalTestingEnd { get; set; }
        public Nullable<System.DateTime> FatStart { get; set; }
        public Nullable<System.DateTime> FatEnd { get; set; }
        public Nullable<System.DateTime> Delivery { get; set; }
        public Nullable<System.DateTime> FatBilling { get; set; }
        public Nullable<System.DateTime> CommissioningStart { get; set; }
        public Nullable<System.DateTime> CommissioningEnd { get; set; }
        public Nullable<System.DateTime> CommissioningBilling { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string PowerLevelDescription { get; set; }
    
        public virtual mdProject mdProject { get; set; }
    }
}
