//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdPanelFunction
    {
        public int PanelID { get; set; }
        public string FunctionType { get; set; }
        public string Make { get; set; }
        public string Type { get; set; }
        public string Specification { get; set; }
        public string CatalogNumber { get; set; }
        public string Remark { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int PanelFunctionID { get; set; }
    
        public virtual mdPanel mdPanel { get; set; }
    }
}
