//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdPanelComponent
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Make { get; set; }
        public string Type { get; set; }
        public string Catalog { get; set; }
        public string TagName { get; set; }
        public string Family { get; set; }
        public string ItemID { get; set; }
        public string PR_NO { get; set; }
        public string GTN_NO { get; set; }
        public string DwgName { get; set; }
        public string Handle { get; set; }
        public Nullable<bool> FreeIssued { get; set; }
        public Nullable<int> ScheeduleHItemID { get; set; }
        public Nullable<bool> Spare { get; set; }
        public string PentaItemID { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual mdAnnunciator mdAnnunciator { get; set; }
        public virtual mdAuxiliaryComponent mdAuxiliaryComponent { get; set; }
        public virtual mdAuxiliaryRelay mdAuxiliaryRelay { get; set; }
        public virtual mdConsumableItem mdConsumableItem { get; set; }
        public virtual mdContractSecondaryDeliverable mdContractSecondaryDeliverable { get; set; }
        public virtual mdMainRelay mdMainRelay { get; set; }
        public virtual mdMeter mdMeter { get; set; }
        public virtual mdTerminalBlock mdTerminalBlock { get; set; }
        public virtual mdTestBlock mdTestBlock { get; set; }
        public virtual mdTransducer mdTransducer { get; set; }
    }
}
