//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdPanel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdPanel()
        {
            this.mdPanelFunctions = new HashSet<mdPanelFunction>();
            this.mdPanels1 = new HashSet<mdPanel>();
        }
    
        public Nullable<int> PanelType_id { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int PanelID { get; set; }
        public string PanelNo { get; set; }
        public string DwgNo { get; set; }
        public string WiringScheduleDwgNo { get; set; }
        public string SipTbGroup { get; set; }
        public string CableScheduleDwgNo { get; set; }
        public string ACPhase { get; set; }
        public bool BusBarProtection { get; set; }
        public bool SyncCircuit { get; set; }
        public bool IsSupplyByPSI { get; set; }
        public bool AnnCircuit { get; set; }
        public bool IndCircuit { get; set; }
        public string SIP_Group { get; set; }
        public string TB_Group { get; set; }
        public string BusVT1 { get; set; }
        public string BusVT2 { get; set; }
        public string VTWireNo1 { get; set; }
        public string VTWireNo2 { get; set; }
        public string MCBTripWireNo1 { get; set; }
        public string MCBTripWireNo2 { get; set; }
        public Nullable<int> PanelSizeID { get; set; }
        public string PentaID { get; set; }
        public Nullable<int> IndArrOrderNo { get; set; }
        public Nullable<int> SyncArrOrderNo { get; set; }
        public Nullable<int> AcArrOrderNo { get; set; }
        public Nullable<int> AnnArrOrderNo { get; set; }
        public Nullable<int> PanelArrOrderNo { get; set; }
        public Nullable<int> IndArrRowId { get; set; }
        public Nullable<int> SyncArrRowId { get; set; }
        public Nullable<int> ACArrRowId { get; set; }
        public Nullable<int> AnnArrRowId { get; set; }
        public Nullable<int> AcSupplyFromPanelID { get; set; }
        public Nullable<int> PanelArrRowId { get; set; }
        public string SyncLeftNegativeFerrule { get; set; }
        public string SyncLeftPossitveFerrule { get; set; }
        public string SyncRightNegativeFerrule { get; set; }
        public string SyncRightPossitveFerrule { get; set; }
    
        public virtual mdArrangementAcLoopRow mdArrangementAcLoopRow { get; set; }
        public virtual mdArrangementAnnunciationRow mdArrangementAnnunciationRow { get; set; }
        public virtual mdArrangementPanelRow mdArrangementPanelRow { get; set; }
        public virtual mdArrangementsIndicationRow mdArrangementsIndicationRow { get; set; }
        public virtual mdArrangementSynchCircuitRow mdArrangementSynchCircuitRow { get; set; }
        public virtual mdBPanel mdBPanel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdPanelFunction> mdPanelFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdPanel> mdPanels1 { get; set; }
        public virtual mdPanel mdPanel1 { get; set; }
        public virtual mdPanelSize mdPanelSize { get; set; }
        public virtual msSubstationStructure msSubstationStructure { get; set; }
        public virtual mdSPanel mdSPanel { get; set; }
        public virtual mdVPanel mdVPanel { get; set; }
    }
}
