//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdPowerTransformer
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int PrimaryEquipmentId { get; set; }
        public string Impd { get; set; }
        public string NoOfWinding { get; set; }
        public string PrimaryCurrentUnit { get; set; }
        public string PrimaryCurrentValue { get; set; }
        public string PrimaryVoltageUnit { get; set; }
        public string PrimaryVoltageValue { get; set; }
        public string RatingUnit { get; set; }
        public string RatingValue { get; set; }
        public string SecondaryCurrentUnit { get; set; }
        public string SecondaryCurrentValue { get; set; }
        public string SecondaryVoltageUnit { get; set; }
        public string SecondaryVoltageValue { get; set; }
        public string TertiaryVoltageUnit { get; set; }
        public string TertiaryVoltageValue { get; set; }
        public string VectorGroup { get; set; }
    
        public virtual mdPrimaryEquipment mdPrimaryEquipment { get; set; }
    }
}
