//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdProjectStakeHolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdProjectStakeHolder()
        {
            this.msStakeHolderContacts = new HashSet<msStakeHolderContact>();
        }
    
        public int Id { get; set; }
        public string StakeholderType { get; set; }
        public string ContactDetailId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual mdProject mdProject { get; set; }
        public virtual msCompany msCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msStakeHolderContact> msStakeHolderContacts { get; set; }
    }
}
