//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdProject()
        {
            this.mdContractPrimaryDeliverables = new HashSet<mdContractPrimaryDeliverable>();
            this.mdContractSecondaryDeliverables = new HashSet<mdContractSecondaryDeliverable>();
            this.mdCustomerDeliverableVoltages = new HashSet<mdCustomerDeliverableVoltage>();
            this.mdExternalStakeHolders = new HashSet<mdExternalStakeHolder>();
            this.mdInternalStakeHolders = new HashSet<mdInternalStakeHolder>();
            this.mdMasterProjectSchedules = new HashSet<mdMasterProjectSchedule>();
            this.mdProjectStakeHolders = new HashSet<mdProjectStakeHolder>();
            this.mdRevisionHistories = new HashSet<mdRevisionHistory>();
            this.mdSubstations = new HashSet<mdSubstation>();
        }
    
        public string ProjectName { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> MprCheckedOn { get; set; }
        public Nullable<System.DateTime> MprApprovedOn { get; set; }
        public Nullable<System.DateTime> MprCreatedOn { get; set; }
        public string ProjectTitle4 { get; set; }
        public string ProjectTitle3 { get; set; }
        public string ProjectTitle2 { get; set; }
        public string ProjectTitle1 { get; set; }
        public string PsiProjectCode { get; set; }
        public string ContractNumber { get; set; }
        public string TenderNumber { get; set; }
        public string ProjectPentaID { get; set; }
        public string PMO_AspNetUserId { get; set; }
        public string ProjectEngineer_AspNetUserId { get; set; }
        public string ProjectManager_AspNetUserId { get; set; }
        public string EngineeringTeamApprovedBy_AspNetUserId { get; set; }
        public string EngineeringTeamCheckedBy_AspNetUserId { get; set; }
        public string EngineeringTeamDesignedBy_AspNetUserId { get; set; }
        public string EngineeringTeamDrawnBy_AspNetUserId { get; set; }
        public string MprCheckedBy_AspNetUserId { get; set; }
        public string MprApprovedBy_AspNetUserId { get; set; }
        public string MprCreatedBy_AspNetUserId { get; set; }
        public string ProjectLockedBy_AspNetUserId { get; set; }
        public string ProjectLockedInMachine { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string MainconAddress { get; set; }
        public string MainconCity { get; set; }
        public string MainconState { get; set; }
        public string MainconPostalCode { get; set; }
        public string MainconCountry { get; set; }
        public string MainconPhone { get; set; }
        public string MainconFax { get; set; }
        public Nullable<int> MainconCompanyId { get; set; }
        public Nullable<bool> Notification { get; set; }
        public string EngineeringManager_AspNetUserId { get; set; }
        public Nullable<System.DateTime> ExternalKickOffDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual AspNetUser AspNetUser7 { get; set; }
        public virtual AspNetUser AspNetUser8 { get; set; }
        public virtual AspNetUser AspNetUser9 { get; set; }
        public virtual AspNetUser AspNetUser10 { get; set; }
        public virtual AspNetUser AspNetUser11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdContractPrimaryDeliverable> mdContractPrimaryDeliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdContractSecondaryDeliverable> mdContractSecondaryDeliverables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdCustomerDeliverableVoltage> mdCustomerDeliverableVoltages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdExternalStakeHolder> mdExternalStakeHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdInternalStakeHolder> mdInternalStakeHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdMasterProjectSchedule> mdMasterProjectSchedules { get; set; }
        public virtual msCompany msCompany { get; set; }
        public virtual msSubstationStructure msSubstationStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdProjectStakeHolder> mdProjectStakeHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdRevisionHistory> mdRevisionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdSubstation> mdSubstations { get; set; }
    }
}
