//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class mdRevisionHistory
    {
        public string RevisionNo { get; set; }
        public string KeyedInByDate { get; set; }
        public string CheckedByDate { get; set; }
        public string ApprovedByDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int RevisionHistoryID { get; set; }
    
        public virtual mdProject mdProject { get; set; }
    }
}
