//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdRemoteEndDetail
    {
        public string SubstationName { get; set; }
        public string BayNos { get; set; }
        public string Address { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<int> VoltageLevelID { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int RemoteEndDetailID { get; set; }
    
        public virtual mdVoltageLevel mdVoltageLevel { get; set; }
    }
}
