//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdSubstation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdSubstation()
        {
            this.mdArrangementAcLoopRows = new HashSet<mdArrangementAcLoopRow>();
            this.mdArrangementAnnunciationRows = new HashSet<mdArrangementAnnunciationRow>();
            this.mdArrangementPanelRows = new HashSet<mdArrangementPanelRow>();
            this.mdArrangementsIndicationRows = new HashSet<mdArrangementsIndicationRow>();
            this.mdArrangementSynchCircuitRows = new HashSet<mdArrangementSynchCircuitRow>();
            this.mdSchematicProjectPaths = new HashSet<mdSchematicProjectPath>();
            this.mdSPanels = new HashSet<mdSPanel>();
            this.mdVoltageLevels = new HashSet<mdVoltageLevel>();
        }
    
        public string SubstationName { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int SubstationID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> ProjectManager { get; set; }
        public Nullable<int> ProjectEngineer { get; set; }
        public Nullable<int> ProjectCoOrdinator { get; set; }
        public string SubstationType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdArrangementAcLoopRow> mdArrangementAcLoopRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdArrangementAnnunciationRow> mdArrangementAnnunciationRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdArrangementPanelRow> mdArrangementPanelRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdArrangementsIndicationRow> mdArrangementsIndicationRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdArrangementSynchCircuitRow> mdArrangementSynchCircuitRows { get; set; }
        public virtual mdProject mdProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdSchematicProjectPath> mdSchematicProjectPaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdSPanel> mdSPanels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdVoltageLevel> mdVoltageLevels { get; set; }
    }
}
