//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdTransducer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdTransducer()
        {
            this.mdTransducerChannelSpecs = new HashSet<mdTransducerChannelSpec>();
        }
    
        public string Channels { get; set; }
        public string ChannelSpec { get; set; }
        public string Class { get; set; }
        public int ID { get; set; }
    
        public virtual mdPanelComponent mdPanelComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdTransducerChannelSpec> mdTransducerChannelSpecs { get; set; }
    }
}
