//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdVoltageLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdVoltageLevel()
        {
            this.mdBays = new HashSet<mdBay>();
            this.mdRemoteEndDetails = new HashSet<mdRemoteEndDetail>();
            this.mdVPanels = new HashSet<mdVPanel>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        public int VoltageLevelID { get; set; }
        public Nullable<int> VoltageLevelValue_Id { get; set; }
        public Nullable<int> SwitchGearType_Id { get; set; }
        public Nullable<int> StationComType_id { get; set; }
        public Nullable<int> BusConfiguration_Id { get; set; }
        public string NominalCurrent { get; set; }
        public string Frequency { get; set; }
        public string FaultLevel { get; set; }
        public string FaultDuration { get; set; }
        public int SubstationID { get; set; }
        public string DrawingCode { get; set; }
        public string BusSegments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdBay> mdBays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdRemoteEndDetail> mdRemoteEndDetails { get; set; }
        public virtual mdSubstation mdSubstation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdVPanel> mdVPanels { get; set; }
        public virtual msSubstationStructure msSubstationStructure { get; set; }
        public virtual msSubstationStructure msSubstationStructure1 { get; set; }
        public virtual msSubstationStructure msSubstationStructure2 { get; set; }
        public virtual msSubstationStructure msSubstationStructure3 { get; set; }
    }
}
