//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msConsumable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msConsumable()
        {
            this.msRequiredQuantities = new HashSet<msRequiredQuantity>();
        }
    
        public string ItemDescription { get; set; }
        public string Manufacturer { get; set; }
        public string Catalog { get; set; }
        public string Type { get; set; }
        public string Rating { get; set; }
        public string ItemsPerUnit { get; set; }
        public string Units { get; set; }
        public string ITEMID { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        public int ConsumableID { get; set; }
        public string PENTA_ID { get; set; }
        public string Field1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msRequiredQuantity> msRequiredQuantities { get; set; }
    }
}
