//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msDrawing
    {
        public Nullable<int> SortingNo { get; set; }
        public string DrawingPath { get; set; }
        public Nullable<int> PanelID { get; set; }
        public string Description { get; set; }
        public int ID { get; set; }
    
        public virtual msSubstationStructure msSubstationStructure { get; set; }
    }
}
