//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msDrawingFunction
    {
        public int ID { get; set; }
        public string DrawingFuncton { get; set; }
        public string Code { get; set; }
        public string EXAMPLE_SHEETS { get; set; }
    }
}
