//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msGenSchemeComponent
    {
        public int ID { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public string Tag { get; set; }
        public string BlockNames { get; set; }
        public string GenTerms { get; set; }
        public string CurrentMake { get; set; }
        public string CurrentCatalog { get; set; }
        public string GenLoc { get; set; }
        public string GenLocDesc { get; set; }
        public string GenTag { get; set; }
        public string GenTagDesc { get; set; }
        public string Loc { get; set; }
        public string Family { get; set; }
    
        public virtual msSubstationStructure msSubstationStructure { get; set; }
    }
}
