//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msInitial
    {
        public string name { get; set; }
        public string Initial { get; set; }
        public byte[] esign { get; set; }
        public string Phone { get; set; }
        public string ExtensionNumber { get; set; }
        public bool DisplayInDrawnBy { get; set; }
        public bool DisplayInDesignedBy { get; set; }
        public bool DisplayInCheckedBy { get; set; }
        public bool DisplayInApprovedBy { get; set; }
        public bool DisplayInManagedBy { get; set; }
        public int ID { get; set; }
    }
}
