//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msLocationDesignation
    {
        public string paneltype { get; set; }
        public string Abbreviation { get; set; }
        public string Symbol { get; set; }
        public bool HavingSyncCircuit { get; set; }
        public bool HavingProtectionCircuit { get; set; }
        public bool HavingAnnunciationDcLoopCircuit { get; set; }
        public bool HavingIndicationDcLoopCircuit { get; set; }
        public int ID { get; set; }
    }
}
