//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msPrimaryEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msPrimaryEquipment()
        {
            this.msPrimaryEquipmentDrawings = new HashSet<msPrimaryEquipmentDrawing>();
        }
    
        public string PrimaryEquipment { get; set; }
        public string Description { get; set; }
        public string PsiStandardID { get; set; }
        public bool IsOptional { get; set; }
        public Nullable<int> BayID { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msPrimaryEquipmentDrawing> msPrimaryEquipmentDrawings { get; set; }
        public virtual msSubstationStructure msSubstationStructure { get; set; }
    }
}
