//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msProtectionFunction
    {
        public string FunName { get; set; }
        public string code { get; set; }
        public string tagcode { get; set; }
        public string table { get; set; }
        public int ID { get; set; }
    }
}
