//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msStakeHolderContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msStakeHolderContact()
        {
            this.mdExternalStakeHolders = new HashSet<mdExternalStakeHolder>();
            this.mdProjectStakeHolders = new HashSet<mdProjectStakeHolder>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string OfficePhone { get; set; }
        public string EmailAddress { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> StakeHolderId { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdExternalStakeHolder> mdExternalStakeHolders { get; set; }
        public virtual msCompany msCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdProjectStakeHolder> mdProjectStakeHolders { get; set; }
    }
}
