//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msSubstationStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msSubstationStructure()
        {
            this.mdBays = new HashSet<mdBay>();
            this.mdPanels = new HashSet<mdPanel>();
            this.mdProjects = new HashSet<mdProject>();
            this.mdVoltageLevels = new HashSet<mdVoltageLevel>();
            this.mdVoltageLevels1 = new HashSet<mdVoltageLevel>();
            this.mdVoltageLevels2 = new HashSet<mdVoltageLevel>();
            this.mdVoltageLevels3 = new HashSet<mdVoltageLevel>();
            this.msBayRelayFunctions = new HashSet<msBayRelayFunction>();
            this.msDrawings = new HashSet<msDrawing>();
            this.msGenSchemeComponents = new HashSet<msGenSchemeComponent>();
            this.msMimics = new HashSet<msMimic>();
            this.msPrimaryEquipments = new HashSet<msPrimaryEquipment>();
            this.msRequiredQuantities = new HashSet<msRequiredQuantity>();
        }
    
        public string Objects { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ObjectType { get; set; }
        public string FullPath { get; set; }
        public Nullable<int> Field1 { get; set; }
        public string Description { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdBay> mdBays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdPanel> mdPanels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdProject> mdProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdVoltageLevel> mdVoltageLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdVoltageLevel> mdVoltageLevels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdVoltageLevel> mdVoltageLevels2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdVoltageLevel> mdVoltageLevels3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msBayRelayFunction> msBayRelayFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msDrawing> msDrawings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msGenSchemeComponent> msGenSchemeComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msMimic> msMimics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msPrimaryEquipment> msPrimaryEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msRequiredQuantity> msRequiredQuantities { get; set; }
    }
}
