//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msTNBApprovedEquipment
    {
        public string Function { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string RecommendedOrderingNo { get; set; }
        public string manufacturer { get; set; }
        public string Version { get; set; }
        public string SGP_Certificate_No_TTC_Action_Sheet_No { get; set; }
        public string OtherLimitations { get; set; }
        public string VoltageLimit_kv { get; set; }
        public string Notes { get; set; }
        public bool Vl_500kV { get; set; }
        public bool Vl_275kV { get; set; }
        public bool Vl_132kV { get; set; }
        public bool Vl_33kV { get; set; }
        public bool Vl_22kV { get; set; }
        public bool Vl_11kV { get; set; }
        public string ReleaseNo { get; set; }
        public int ID { get; set; }
    }
}
