//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsiMprODataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msVoltageLevel
    {
        public Nullable<int> Level { get; set; }
        public string Code { get; set; }
        public string Units { get; set; }
        public string CurrentType { get; set; }
        public int ID { get; set; }
    }
}
